[request.py] 2020-08-23 15:27:23 request.request 第39行 ERROR:接口调用异常:HTTPConnectionPool(host='39.98.138.157', port=5000): Max retries exceeded with url: /api/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000009F65788>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
